# NAME: Ian Conceicao
# EMAIL: IanCon234@gmail.com
# ID: 505153981

default:
	gcc lab1a.c -o lab1a -Wall -Wextra

dist:
	tar -czvf lab1a-505153981.tar.gz lab1a.c README Makefile

clean:
	rm -f lab1a lab1a-505153981.tar.gz