#NAME: Ian Conceicao
#EMAIL: IanCon234@gmail.com
#ID: 505153981

.SILENT:

default:
	chmod +x lab3b.sh
	-ln lab3b.sh lab3b
	echo "Make succeeded"

dist:
	tar -czvf lab3b-505153981.tar.gz lab3b.py lab3b.sh Makefile README

clean:
	rm -f lab3b *.tar.gz