#NAME: Ian Conceicao
#EMAIL: IanCon234gmail.com
#ID: 505153981

default:
	gcc -Wall -Wextra lab3a.c -o lab3a -lm
	
dist:
	tar -czvf lab3a-505153981.tar.gz lab3a.c README Makefile ext2_fs.h

clean:
	rm -f lab3a-505153981.tar.gz lab3a