#NAME: Ian Conceicao
#EMAIL: IanCon234@gmail.com
#ID: 505153981

default:
	tar -czvf lab4a-505153981.tar.gz my_beaglebone.jpg connected.png copy.png build_run.png git.png README Makefile

dist: default
	

clean:
	rm -f lab4a-505153981.tar.gz
